/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Senai
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLisCursos = new javax.swing.JButton();
        btnCaCurso = new javax.swing.JButton();
        btnCaArea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLisCursos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLisCursos.setText("LISTAR CURSOS");
        btnLisCursos.setBorderPainted(false);
        btnLisCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLisCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLisCursosActionPerformed(evt);
            }
        });
        jPanel1.add(btnLisCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 175, 35));

        btnCaCurso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCaCurso.setText("CADASTRAR CURSOS");
        btnCaCurso.setBorderPainted(false);
        btnCaCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 35));

        btnCaArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCaArea.setText("CADASTRAR AREAS");
        btnCaArea.setBorderPainted(false);
        btnCaArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaAreaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 175, 35));

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 290, 100));

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 290, 90));

        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 290, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaAreaActionPerformed
        TelaArea objTelaArea = new TelaArea();
        objTelaArea.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCaAreaActionPerformed

    private void btnCaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaCursoActionPerformed
        TelaCursos objTelaCursos = new TelaCursos();
        objTelaCursos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCaCursoActionPerformed

    private void btnLisCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLisCursosActionPerformed
        TelaLista objTelaLista = new TelaLista();
        objTelaLista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLisCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaArea;
    private javax.swing.JButton btnCaCurso;
    private javax.swing.JButton btnLisCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
